apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: java-demo-hpa
  labels:
    app: java-demo
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: java-demo-deployment
  minReplicas: 2
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 90
